auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: 夏夜dCom
url: http://Sunnylshiny.github.io/
feed: /atom.xml
author_info: <a href="http://Sunnylshiny.github.io">XiaYe</a>
